[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --browser chromium
    --headed
    --strict-markers
    --alluredir=allure-results

markers =
    smoke: Smoke tests
    regression: Regression tests
    ui: UI tests
    no_ads_block: Run test without ad blocking